### PR TITLE
Use singletons in sensing

### LINKED ISSUE #60: Sync should utilize singletons instead of re-instantiating : fetcher, processor and uploader

### PR DESCRIPTION
**Pull request by MJ1998**
Fixes #60 #12 

Created singletons as per : https://www.baeldung.com/kotlin/singleton-classes#1-companion-object

For easy integration, the configuration is now provided from `SensingEngineConfiguration.Provider` interface. This interface is implemented by the Application class which can be accessed via the `applicationContext` variable.

Small change so that the application works even when no `local.properties` file is provided.

The interfaces and singleton instances are public whereas the implementations are private.

TESTED:-
Uploaded data once. Closed app. Opened and uploaded again. Works as intended!

### CODE REVIEW

**Review by chandrashekar-s — APPROVED** [review]
The changes look fine @MJ1998. May be you can also do similar changes in places where Singleton classes are present. Created this [ticket](https://github.com/google-research/CVD-paper-mobile-camera-example/issues/69) for the same. You can do it in a separate PR though.

**Comment by MJ1998** [comment]
Wondering if all singletons should be in one place, for example, `SensingEngineProvider` ?
@chandrashekar-s

**Comment by chandrashekar-s** [comment]
> Wondering if all singletons should be in one place, for example, `SensingEngineProvider` ? @chandrashekar-s

Should be fine to have in individual classes, probably to have a better context.

**Review by chandrashekar-s — APPROVED** [review]
LGTM @MJ1998

**Pull request merged**
